# -*- coding: utf-8 -*-
"""Proyecto_Multiflujo_Ambulancias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Wo5jGB9j8t_KG2424KGWBF_iP-GnfRu
"""

!pip install osmnx pulp streamlit pyngrok folium networkx

import osmnx as ox
import networkx as nx
import random
import pandas as pd

# Coordenadas del centro de Medellín (puedes cambiarlas por tu zona)
lat, lon = 6.2442, -75.5812

# Descargar red vial (1 km alrededor)
G = ox.graph_from_point((lat, lon), dist=500, network_type='drive')

# Convertir a grafo no dirigido (versión actual de OSMnx)
G = nx.Graph(G)

# Mostrar número de nodos y aristas
print(f"Nodos: {len(G.nodes)}")
print(f"Aristas: {len(G.edges)}")

# Elegir nodo central como base de ambulancias
base = list(G.nodes)[0]

# Crear puntos aleatorios como emergencias
n_incidentes = 3
destinos = random.sample(list(G.nodes), n_incidentes)

# Tipos de urgencia
tipos = ["leve", "media", "critica"]
urgencias = dict(zip(destinos, tipos))

urgencias

for u, v, data in G.edges(data=True):
    data["C_min"] = random.randint(30, 50)
    data["C_max"] = random.randint(60, 100)
    data["capacity"] = random.randint(data["C_min"], data["C_max"])

import pulp

# Crear modelo
model = pulp.LpProblem("Rutas_Ambulancias_Multiflujo", pulp.LpMinimize)

# Variables: flujo de cada ambulancia por cada arco
flows = {}
for i, destino in enumerate(destinos):
    for u, v in G.edges():
        flows[(i, u, v)] = pulp.LpVariable(f"f_{i}_{u}_{v}", 0, 1, cat='Binary')

# Función objetivo: minimizar costo total (distancia * flujo)
costos = nx.get_edge_attributes(G, "length")
objective = pulp.lpSum([flows[(i, u, v)] * costos.get((u, v), 1)
                        for i in range(n_incidentes) for u, v in G.edges()])
model += objective

# Restricciones de flujo: cada ambulancia sale de la base y llega a su destino
for i, destino in enumerate(destinos):
    for n in G.nodes():
        in_flow = pulp.lpSum([flows[(i, u, n)] for u in G.neighbors(n) if (i, u, n) in flows])
        out_flow = pulp.lpSum([flows[(i, n, v)] for v in G.neighbors(n) if (i, n, v) in flows])

        if n == base:
            model += (out_flow - in_flow == 1)
        elif n == destino:
            model += (in_flow - out_flow == 1)
        else:
            model += (in_flow - out_flow == 0)

# Resolver
model.solve(pulp.PULP_CBC_CMD(msg=False))
print("Estado:", pulp.LpStatus[model.status])

import folium
from shapely.geometry import LineString, Point

# Crear mapa centrado en la base
x, y = G.nodes[base]['x'], G.nodes[base]['y']
m = folium.Map(location=[y, x], zoom_start=15)

# Agregar TODAS las calles en gris
for u, v, data in G.edges(data=True):
    if 'geometry' in data:
        coords = [(lat, lon) for lon, lat in data['geometry'].coords]
    else:
        coords = [(G.nodes[u]['y'], G.nodes[u]['x']), (G.nodes[v]['y'], G.nodes[v]['x'])]
    folium.PolyLine(coords, color='gray', weight=2, opacity=0.5).add_to(m)

# Agregar las aristas seleccionadas en rojo
for (u, v) in edges_selected:
    if G.has_edge(u, v):
        data = G.get_edge_data(u, v)
        if 'geometry' in data:
            coords = [(lat, lon) for lon, lat in data['geometry'].coords]
        else:
            coords = [(G.nodes[u]['y'], G.nodes[u]['x']), (G.nodes[v]['y'], G.nodes[v]['x'])]
        folium.PolyLine(coords, color='red', weight=5, opacity=0.9).add_to(m)

# Marcar base (origen)
folium.Marker(
    location=[G.nodes[base]['y'], G.nodes[base]['x']],
    popup="Base de ambulancias",
    icon=folium.Icon(color='blue', icon='plus')
).add_to(m)

# Marcar destinos (incidentes)
for destino, tipo in urgencias.items():
    folium.Marker(
        location=[G.nodes[destino]['y'], G.nodes[destino]['x']],
        popup=f"Incidente {tipo}",
        icon=folium.Icon(color='red' if tipo == 'critica' else 'orange' if tipo == 'media' else 'green')
    ).add_to(m)

m

with open("requirements.txt", "w") as f:
    f.write(
        "osmnx==1.9.2\n"
        "networkx\n"
        "pulp\n"
        "streamlit\n"
        "folium\n"
        "pandas\n"
        "pyngrok\n"
    )